<?php

$backUrl = $this->url('backend/config/square');

$this->setup(array(
    'title' => 'Delete this rink',
    'panel' => 'centered-panel large-sized',
    'back' => array(
        $this->option('subject.square.type.plural') => $backUrl,
    ),
));

?>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to delete this rink?') ?></span></p>

    <p class="no-wrap">
        <a href="<?= $this->url('backend/config/square/delete', ['sid' => $this->sid], ['query' => ['confirmed' => 'true']]) ?>" class="default-button">
            <span class="symbolic symbolic-cross"><?= $this->t('Yes, delete this rink') ?></span>
        </a>

        &nbsp;

        <a href="<?= $backUrl ?>" class="default-button"><?= $this->t('No, go back') ?></a>
    </p>

    <?php if ($this->squareBookings): ?>
        <p class="yellow"><?= $this->t('Since this rink already has bookings, it will be set to disabled but kept in the database') ?></p>
    <?php endif; ?>
</div>