<?php

$this->setup(array(
    'title' => 'Forgot your password?',
    'panel' => 'centered-panel',
    'back' => true,
    'links' => array(
        'Login' => $this->url('user/login'),
    ),
));

?>

<div>
    <h1><?= $this->t('Forgot your password?') ?></h1>

    <div class="separator-small"></div>

    <p>
        Please contact the Secretary of the LCE Bowls Club to reset your password.
    </p>

    <p>
        The Secretary will set a temporary password for you. Once you have logged in with it,
        please change it to a password of your own under your account settings.
    </p>
</div>
