<?php

$squareType = $this->option('subject.square.type');
$square = $this->square;

if ($this->notBookableReason) {
    $reason = $this->notBookableReason;
} else {
    $reason = $this->t('This %s is already occupied.');
}

echo sprintf('<p><span class="red">' . $reason . '</span></p>', $squareType);

if (count($this->bookings) == 1) {
    $booking = current($this->bookings);
    $namesVisible = $this->user && $booking->getExtra('user');

    if ($namesVisible) {
        $bookingTypeColor = $this->bookingTypeService->getTypeColor($booking->getMeta('type'));
        $style = $bookingTypeColor ? ' style="color: ' . $bookingTypeColor . ';"' : '';

        echo '<p' . $style . '><b>' . $this->t('Players') . ':</b> ' . $this->calendarBookingNames($booking) . '</p>';
    }
}
