<?php

$this->headScript()->appendFile($this->basePath('js/controller/frontend/index.min.js'));

?>

<div id="green-heading" class="panel no-print">
    <a href="<?= $this->url('frontend') ?>" class="default-button"><?= $this->t('All greens') ?></a>

    <?php if ($this->green !== null): ?>
        <span class="green-heading-name"><?= $this->escapeHtml(sprintf($this->t('Green %s'), $this->green)) ?></span>

        <?php if ($this->greenClosed): ?>
            <div class="green-closed-banner">
                <?= $this->escapeHtml(sprintf($this->t('Green %s is closed on %s'), $this->green, $this->dateFormat($this->dateStart, IntlDateFormatter::FULL))) ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>

<div id="calendar-toolbar" class="no-print">
    <div id="calendar-toolbar-datepicker" class="panel">
        <?= $this->partial('frontend/index/datepicker.phtml', ['dateStart' => $this->dateStart, 'dateNow' => $this->dateNow, 'squaresFilter' => $this->squaresFilter]) ?>
    </div>

    <div id="calendar-toolbar-userpanel" class="panel">
        <?php if ($this->user): ?>
            <?= $this->partial('frontend/index/userpanel.online.phtml', ['user' => $this->user]) ?>
        <?php else: ?>
            <?= $this->partial('frontend/index/userpanel.offline.phtml') ?>
        <?php endif; ?>
    </div>
</div>

<?= $this->calendar ?>
